"""Implementation defaults for unset configuration values."""
DEFAULT_CONFIG = {'model': {'student': '/path/to/diffusion-student',
           'teacher': '/path/to/autoregressive-teacher',
           'copy_pad_embedding_to_mask': False},
 'data': {'path': '/path/to/train.jsonl',
          'epochs': 1,
          'apply_chat_template': True,
          'enable_thinking': False,
          'correctness_fn': None},
 'output_dir': 'outputs/d-opd',
 'block_size': 4,
 'rollout': {'prompts_per_step': 128,
             'max_tokens': 4000,
             'max_prompt_tokens': 2000,
             'max_active': 32,
             'gpu_memory_utilization': 0.8,
             'temperature': 1.0,
             'top_p': 1.0,
             'top_k': 0,
             'remasking_strategy': 'low_confidence_dynamic',
             'dynamic_threshold': 0.9,
             'response_aligned_blocks': False},
 'training': {'lambda': 0.5,
              'correctness_gate': True,
              'candidate_top_k': 16,
              'loss_top_k': 16,
              'score_chunk_size': 128,
              'batch_size_per_gpu': 1,
              'gradient_accumulation_steps': 1,
              'learning_rate': 1e-05,
              'warmup_steps': 5,
              'min_lr_scale': 0.1,
              'max_grad_norm': 1.0,
              'gradient_checkpointing': True,
              'exclude_eos_from_loss': True,
              'save_every': 10,
              'keep_checkpoints': 1,
              'cache_max_bytes': 17179869184,
              'require_visible_future': True,
              'preserve_zero_support': True},
 'wandb': {'enabled': False,
           'project': 'd-OPD',
           'run_name': 'd-opd',
           'run_id': None},
 'seed': 10086,
 'denoise_step': None}
